App_Login/urls.py
from django.urls import path
from . import views

app_name  = 'App_Login'

urlpatterns = [
    path('signup/', views.signup, name = "signup"),
    path('signin/', views.login_page, name = 'signin'),
    path('logout/' , views.logout_user, name = "logout" ),
    path('profile/' , views.profile, name = "profile" ),
    path('change-profile/' , views.user_change, name = "user_change" ),
    path('password/' , views.pass_change, name = "pass_change" ),
    path('changeprofileimage/' , views.add_pro_pic, name = "add_pro_pic"),
    path('change-picture/' , views.change_pro_pic, name = "change_pro_pic"),

]

Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('', views.index, name = "index")
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete= models.CASCADE)
    profile_pic = models.ImageField(upload_to = 'profile_pic')

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile


class SignupForm(UserCreationForm):
    email = forms.EmailField(label = "Email Address", required=True)
    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name', 'last_name', 'password')


class Profilepic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic']

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm,AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import SignupForm, UserProfileChange,Profilepic
# Create your views here.


def signup(request):
    form  = SignupForm()
    registered = False
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            registered = True
    
    dict = { 'form': form, 'registered': registered}

    return render(request, 'App_Login/signup.html', context = dict )


def login_page(request):
    form  = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username, password = password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'App_Login/login.html', context = {'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:signin'))

@login_required
def profile(request):
    return render(request,'App_Login/profile.html', context  = {})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance = current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST,instance = current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance = current_user)
    return render(request, 'App_Login/change_profile.html', context={'form':form})

@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form  = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data = request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_login/pass_change.html', context = {'form':form, 'changed': changed})

        

@login_required
def add_pro_pic(request):
    form  = Profilepic()
    if request.method == "POST":
        form = Profilepic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit= False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request,'App_Login/profile_pic_add.html',context = {'form':form})
    
        

@login_required
def change_pro_pic(request):
    form = Profilepic(instance = request.user.user_profile)
    if request.method == "POST":
        form = Profilepic(request.POST, request.FILES, instance = request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request,'App_Login/profile_pic_add.html',context = {'form':form})

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} change User profile {% endblock %}


{% block body_block %} 

<h2>Change Profile</h2>

<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Change" class = "btn btn-primary btn-sm">
</form>
{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Login page {% endblock %}

{% block body_block %} 

    <h2>Fill Your Details Here</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-success btn-sm"type="submit" value="Login">
    </form>


{% endblock %}

templates/App_Login/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Pass change page {% endblock %}


{% block body_block %} 


{% if changed %}
<div class="alert alert-success">
    password change sucessfully
</div>
{% endl if %}
<h2>change password</h2>

<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value=" Change Password" class = "btn btn-primary btn-sm">
</form>
{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile Page {% endblock %}

{% block body_block %}
<link href="{% static '/css/profile.css' %}" rel="stylesheet">

<div class = "myprofile">
    <h2 id = "profile-text">My Profile</h2>
</div>


<div class="row card-center">

    <div class="col-4">
        {% if user.user_profile %}
        <img src="/Media/{{user.user_profile.profile_pic}}"width="150" height="180" class= "rounded-circle left-shift">
        <br><br> 
        <a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-outline-secondary left-shift">ChangeProfile pic</a>

        {% else %}
        <img src="/Media/Admin.png" width="120px" class= "rounded-circle left-shift">
        <br><br>
        <a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-outline-secondary left-shift" style="margin-left: 53px;">ChangeProfile pic</a>
        {% endif %}
    </div>

    <div class="col-8">
        <p>First Name</p>
        <p class = "textfield">{{user.first_name}}</p>
        <p>Username</p>
        <p class = "textfield">{{user.username}}</p>
        <p>Email </p>
        <p class = "textfield">{{user.email}}</p>
        <a href="{% url 'App_Login:user_change' %}" class="btn btn-outline-success">Update</a>
    </div>
</div>
<br>



{% endblock %}

templates/App_Login/profile_pic_add.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Profile Pic Update {% endblock %}

{% block body_block %} 

    <h2>Add Your Profile Picture</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-success btn-sm"type="submit" value="Add Picture">
    </form>


{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Register {% endblock %}

{% block body_block %} 
{% if registered %}

<div class="alert alert-success">
    Account Created Successfully <a href =  "{% url 'App_Login:signin' %}"> Login Here</a>
</div>
{% else %}
<h1>Create New Account</h1>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-success btn-sm" type="submit" value="Submit">
    </form>
<br>
<p>Already registerd? <a href = "{% url 'App_Login:signin' %}">Login Here</a></p>

{% endif %}
{% endblock %}