App_Blog/urls.py
from django.urls import path
from . import views
app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name = "blog_list"),    
    path('write/', views.CreateBlog.as_view(), name = "blog/create_blog/"),    
    path('blog_details/<str:slug>/', views.blog_detail, name = "blog_detail"), 
    path('liked/<pk>/', views.liked, name = "liked_post"),    
    path('unliked/<pk>/', views.unliked, name = "unliked_post"), 
    path('my-blog/', views.MyBlog.as_view(), name = "myblog"),    
    path('Edit-blog/<pk>/', views.UpdateBlog.as_view(), name = "edit_blog"),    



]

App_Login/urls.py
from django.urls import path
from . import views

app_name  = 'App_Login'

urlpatterns = [
    path('signup/', views.signup, name = "signup"),
    path('signin/', views.login_page, name = 'signin'),
    path('logout/' , views.logout_user, name = "logout" ),
    path('profile/' , views.profile, name = "profile" ),
    path('change-profile/' , views.user_change, name = "user_change" ),
    path('password/' , views.pass_change, name = "pass_change" ),
    path('changeprofileimage/' , views.add_pro_pic, name = "add_pro_pic"),
    path('change-picture/' , views.change_pro_pic, name = "change_pro_pic"),

]

Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('', views.index, name = "index")
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-10/css/all.min.css" rel = "stylesheet">
    <link href="{% static '/css/owl.carousel.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">

    <title>
        {% block title %}
            Blog
        {% endblock %}
    </title>
  </head>
  <body> 
        <nav class = "navbar navbar-expand-sm bg-dark navbar-dark" style="padding-right: 6rem; height:4.5rem; font-size: 18px;">
            
            <div class="navbar-header page-scroll">
                <a class="navbar-brand" href="{% url 'index' %}" style = "padding-left: 20px;">Blog Chain</a>
            </div>
            
            <ul class="nav navbar-nav ms-auto">
                <li class="nav-item active">
                    <a class = "nav-link" href="{% url 'index' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class = "nav-link" href="{% url 'App_Blog:blog/create_blog/' %}">Write Blog</a>
                </li>
                <li class="nav-item active">
                    <a class = "nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
                </li>
                <li class="nav-item active">
                    <a class = "nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class = "nav-link" href="{% url 'App_Login:signup' %}">SignUp</a>
                </li>
                <li class="nav-item active">
                    <a class = "nav-link" href="{% url 'App_Login:signin' %}">Login</a>
                </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">
                    {{user.username}}
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'App_Blog:myblog' %}">My Blog</a></li> 
                  <li><a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a></li>
                </ul>
            </div>
            {% endif %}
        </nav>
        
       
        <div class="container" style="padding-top:20px;">
            {% block body_block %}

            {% endblock %}

        </div>
    <script src="{% static '/js/jquery.js' %}" ></script>    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src = "{% static '/js/owl.carousel.min.js' %}"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <script>
       $(document).ready(function(){
  $(".owl-carousel").owlCarousel(
  {
        loop: true,
            autoplay: true,
            nav: false,

  responsive : {

    0 : {
        items:1,
        nav:true
        },

    600 : {
        items: 2,
        nav:false
    },
    1000 : {
        items: 4,
        nav:true,
        loop:false
    }
}

  }
  );
});


    </script>
  </body>
</html>