App_Blog/urls.py
from django.urls import path
from . import views
app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name = "blog_list"),    
    path('write/', views.CreateBlog.as_view(), name = "blog/create_blog/"),    
    path('blog_details/<str:slug>/', views.blog_detail, name = "blog_detail"), 
    path('liked/<pk>/', views.liked, name = "liked_post"),    
    path('unliked/<pk>/', views.unliked, name = "unliked_post"), 
    path('my-blog/', views.MyBlog.as_view(), name = "myblog"),    
    path('Edit-blog/<pk>/', views.UpdateBlog.as_view(), name = "edit_blog"),    



]

Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('', views.index, name = "index")
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name= "Put a title")
    slug = models.SlugField(max_length = 264, unique=True)
    blog_content = RichTextField(blank=True,null=True)
    blog_image = models.ImageField(upload_to = 'blog_images', verbose_name = "Blog Image" )
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE, related_name = 'blog_comment')
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)  


class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE, related_name = 'liked_blog')
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'liker_user')
    

App_Blog/forms.py
from django import forms
from .models import Blog,Comment

class Commentform(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

App_Blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import (CreateView, DetailView, UpdateView, ListView, TemplateView, DeleteView) 
from .models import Blog,Comment,Likes
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from .forms import Commentform
# Create your views here.

class MyBlog(LoginRequiredMixin,TemplateView):
    template_name = 'App_Blog/my_blogs.html'

class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'App_Blog/edit_blog.html'
    
    def get_success_url(self, **kwargs):
        return reverse_lazy('App_Blog:blog_detail', kwargs = {'slug': self.object.slug})

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/blog_list.html'
    queryset = Blog.objects.order_by("-publish_date")

class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'App_Blog/createblog.html'
    fields = ('blog_title', 'blog_content', 'blog_image')

    def form_valid(self,form):
        blog_obj = form.save(commit = False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ","-") + "-" + str(uuid.uuid4()) 
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

def blog_detail(request, slug):
    blog = Blog.objects.get(slug = slug)
    comment_form = Commentform()
    already_liked = Likes.objects.filter(blog = blog,user = request.user)
    if already_liked:
        liked = True
    else:
        liked = False

    if request.method == 'POST':
        comment_form  = Commentform(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('App_Blog:blog_detail',kwargs={'slug':slug}))
    return render(request,'App_Blog/blog_detail.html',context = {'blog':blog, 'comment_form':comment_form, 'liked' : liked})

@login_required
def liked(request,pk):
    blog = Blog.objects.get(pk = pk)
    user = request.user
    already_liked = Likes.objects.filter(blog = blog, user = user)
    if not already_liked:
        liked_post = Likes(blog = blog,user = user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Blog:blog_detail',kwargs={'slug':blog.slug}))


@login_required
def unliked(request,pk):
    blog= Blog.objects.get(pk = pk)
    user = request.user
    already_liked = Likes.objects.filter(blog = blog ,user = user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog_detail',kwargs={'slug':blog.slug}))

templates/App_Blog/blog_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Blog Details{% endblock %}

{% block body_block %}
<div class="row">
    <div class = "col-sm-6">
        <h2>{{blog.blog_title}}</h2>
        <h4>Posted By: {{blog.author}}</h4>
        <i><h6>Published On: {{blog.publish_date}}</h6></i>
        <i><h6>Updated On: {{blog.update_date}}</h6></i>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} comments</h6>
    </div>

    <div class = "col-sm-6">
        <img src="/Media/{{blog.blog_image}}" width="100%" >
    </div>
    <div>
        <p>{{blog.blog_content | linebreaks}}</p>
    </div>

    <hr>
    {% if not liked %}
    <a href="{% url 'App_Blog:liked_post' pk=blog.pk %}">
        <i class="far fa-thumbs-up ra-2x"></i>
    </a>
    {% else %}
    <a href="{% url 'App_Blog:unliked_post' pk=blog.pk %}">
        <i class="far fa-thumbs-down ra-2x"></i>
    </a>
    {% endif %}

    <div class="row">
        <div class="col-sm-6">
            <h5>Comments:</h5>
            {% for comment in blog.blog_comment.all %}
            <p><a href="">{{comment.user}}</a></p>
            <b>{{comment.comment}}</b><br>
            <h6><i>{{comment.comment_date}}</i></h6>
            {% endfor %}

        </div>
        <div class="col-sm-6">
            <form action="" method="post">
                {% csrf_token %}
                {{comment_form | crispy}}
                <input type="submit" value="Comment"class  = "btn btn-primary btn-sm">
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filter %}
{% block title %} Home {% endblock %}

{% block body_block %} 

<h4 class="mb-4 mt-5 text-center" style = "font-size:30px"><strong>Popular Posts</strong></h4>
<hr>
<div class="owl-carousel" style = "margin-top:30px">
  
  {% for cat in blogs %}

    <div class = "card item" style="margin-left:34px;">

        <div class ="img-container">

            <img src="/Media/{{cat.blog_image}}" class="responsive-img" alt="" width="100%">

        </div>
            <div class="card-content">
                <div class="card-title">
                   {{cat.title}}

                </div>

                <p class = "truncate">{{cat.blog_content| carousel_filter | linebreaks}}</p>
                 <div class="container center-align mt20">
                  <a href="{% url 'App_Blog:blog_detail' slug=cat.slug %}" class="btn btn-primary" style="margin-left : 90px;">Read</a>
            </div>
            </div>

    </div>

  {%endfor%}

  <div class="owl-dots">
    <div class="owl-dot active"><span></span></div>
    <div class="owl-dot"><span></span></div>
    <div class="owl-dot"><span></span></div>
</div>
</div>
<hr>
{% comment %}
<!-- <section class = "text-center">

    <h4 class =  "mb-5"><strong>Lastest posts</strong></h4>
   
    <div class="row">
        {% for blog in blogs %}
        <div class="col-lg-4 col-md-12 mb-4" style = "float:left;">
            <div class="card">
                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                    <img src="/Media/{{blog.blog_image}}" alt="{{blog.blog_title}}" class="img-fluid" title = "{{blog.blog_title}}" width = 100%>
                    <a href="#!">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                      </a>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{blog.blog_title}}</h5>
                    <p class="card-text">
                        {{blog.blog_content | range_filter| linebreaks}}
                    </p>
                    <a href="{% url 'App_Blog:blog_detail' slug=blog.slug %}" class="btn btn-primary">Read</a>
                </div>
        </div>
        
   
    </div>

</section> -->
{% endcomment %}

<h4 class="mb-5 mt-5 text-center" style = "font-size:30px"><strong>Latest Posts</strong></h4>

{% for blog in blogs %}

<div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="/Media/{{blog.blog_image}}" alt="{{blog.blog_title}}" class="img-fluid" title = "{{blog.blog_title}}" width = 100%>
      </div>
      <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">{{blog.blog_title}}</h5>
            <p class="card-text">
                {{blog.blog_content | range_filter| linebreaks}}
            <a href="{% url 'App_Blog:blog_detail' slug=blog.slug %}" style="position: absolute; float: left; margin-left:15%">Read more</a>
            </p>
            <h6 >Posted By: <a href=""> {{blog.author}}</a></h6>
            <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} comment</h6>
          <p class="card-text">
            <small class="text-muted">{{blog.publish_date}}</small>
          </p>
         
        </div>
        
      </div>
    </div>
  </div>




<!-- <h6>{{blog.publish_date}}</h6>
<div class="row">
    <div class="col-sm-4">
        <img src="/Media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title = "{{blog.blog_title}}" width = 100%>
    </div>
    <div class="col-sm-8">
        <p>{{blog.blog_content | range_filter| linebreaks}} 
            <a href="{% url 'App_Blog:blog_detail' slug=blog.slug %}">Read more</a>
        </p>
        <h6>Posted By: <a href=""> {{blog.author}}</a></h6>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} comment</h6>
    </div>
</div> -->
{% endfor %}
{% endblock %}

templates/App_Blog/createblog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create Blog {% endblock %}

{% block body_block %}
<h2>Write Your Blog Here</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form|crispy}}
    <input type="submit" value="Publish" class = "btn btn-success btn-sm">
</form>



{% endblock %}

templates/App_Blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Edit Blog {% endblock %}

{% block body_block %}

{% if blog.author == user %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}

    {{form.media}}
    <button type = "submit" class = "btn btn-info btn-sm"> Update </button>

</form>
{% else %}
<p> You are not allowed to view this page </p>

{% endif %}
{% endblock %}

templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filter %}
{% block title %} My Blog {% endblock %}

{% block body_block %}

{% for blog in user.post_author.all %}
<h2>{{blog.blog_title}}</h2>
<div class="row">
    <div class="col-sm-4">
        <img src="/Media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width = "100%">
    </div>

    <div class="col-sm-8">
        <p>{{blog.blog_content | range_filter| linebreaks}} 
            <a href="{% url 'App_Blog:blog_detail' slug=blog.slug %}">Read more</a>
        </p>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} comments</h6>
    </div>
</div>

<hr>
<a href="{% url 'App_Blog:edit_blog' pk=blog.pk %}" class = "btn btn-info btn-sm" >Edit</a>
{% endfor %}



{% endblock %}